### ISSUE TITLE
use jsonp to access to feed.php

### ISSUE THREAD

**Issue by andibraeu** [fossasia/feed.api.fossasia.net#3]
TODO from former pull request: use jsonp instead of header('Access-Control-Allow-Origin: *'); to allow cross origin access to feed.php

**Comment by zyzo** [comment]
I'm facing as the return type is xml and needs to be wrapped as a javascript string parameter, otherwise client-side calling `jQuery.ajax` just throw error. 

The proposed solution is to convert the xml file on the server side so that the string can fit in 1 double-quote : 
       * convert all double quotes `"` to simple quotes `'`
       * add a slash `\` at the end of line to enable javascript multiline string

**Comment by zyzo** [comment]
test demo up-to-date http://feed-fossasia-api.herokuapp.com/feed.php

**Comment by zyzo** [comment]
Reopen until merged to master.
